<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>oneroster-bootcamp</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>3.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>3.2.2</version>
        </dependency>
        <!-- OAuth 2.0 Authorization Server -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-authorization-server</artifactId>
            <version>3.2.2</version>
        </dependency>
        <!-- Oauth 2.0 Resource Server -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
            <version>3.2.2</version>
        </dependency>
        <!-- Fake data generator-->
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>1.0.2</version>
        </dependency>
        <!-- Swagger -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-common</artifactId>
            <version>2.5.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <mainClass>org.oneedtech.oneroster.bootcamp.OneRosterServer</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.12.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                https://purl.imsglobal.org/spec/or/v1p2/schema/openapi/onerosterv1p2rostersservice_openapi3_v1p0.json</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>org.oneedtech.oneroster.bootcamp.api</apiPackage>
                            <modelPackage>org.oneedtech.oneroster.bootcamp.model</modelPackage>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <!-- <generateSupportingFiles>false</generateSupportingFiles> -->
                            <openapiNormalizer>
                                SIMPLIFY_ANYOF_STRING_AND_ENUM_BRANCH=true,SIMPLIFY_ONEOF_ANYOF=true
                            </openapiNormalizer>
                            <typeMappings>
                                <typeMapping>Education_level=String</typeMapping>
                                <typeMapping>Education_creditType=String</typeMapping>
                                <typeMapping>CollectionTemplate_collectionType=String</typeMapping>
                                <typeMapping>CollectionTemplate_level=String</typeMapping>
                                <typeMapping>CollectionTemplate_creditType=String</typeMapping>
                                <typeMapping>ComponentTemplate_componentType=String</typeMapping>
                                <typeMapping>ComponentTemplate_level=String</typeMapping>
                                <typeMapping>ComponentTemplate_creditType=String</typeMapping>
                                <typeMapping>CourseTemplate_courseType=String</typeMapping>
                                <typeMapping>CourseTemplate_level=String</typeMapping>
                                <typeMapping>CourseTemplate_creditType=String</typeMapping>
                                <typeMapping>EducationOffering_offeringType=String</typeMapping>
                                <typeMapping>EducationOffering_offeringFormat=String</typeMapping>
                                <typeMapping>EducationOffering_synchronicity=String</typeMapping>
                                <typeMapping>CollectionOffering_offeringType=String</typeMapping>
                                <typeMapping>CollectionOffering_offeringFormat=String</typeMapping>
                                <typeMapping>CollectionOffering_synchronicity=String</typeMapping>
                                <typeMapping>ComponentOffering_offeringType=String</typeMapping>
                                <typeMapping>ComponentOffering_offeringFormat=String</typeMapping>
                                <typeMapping>ComponentOffering_synchronicity=String</typeMapping>
                                <typeMapping>CourseOffering_offeringType=String</typeMapping>
                                <typeMapping>CourseOffering_offeringFormat=String</typeMapping>
                                <typeMapping>CourseOffering_synchronicity=String</typeMapping>
                                <typeMapping>AcademicSession_sessionType=String</typeMapping>
                                <typeMapping>RoleEnablement_role=String</typeMapping>
                                <typeMapping>Enrollment_role=String</typeMapping>
                                <typeMapping>Enrollment_offeringType=String</typeMapping>
                                <typeMapping>Enrollment_enrollmentStatus=String</typeMapping>
                                <typeMapping>Affiliation_role=String</typeMapping>
                                <typeMapping>Affiliation_affiliationStatus=String</typeMapping>
                                <typeMapping>Person_gender=String</typeMapping>
                                <typeMapping>Agents_agentType=String</typeMapping>
                                <typeMapping>PersonNameEntry_nameType=String</typeMapping>
                                <typeMapping>IdentifierEntry_identifierType=String</typeMapping>
                                <typeMapping>TypedAddress_addressType=String</typeMapping>
                                <typeMapping>OptionallyTypedAddress_addressType=String</typeMapping>
                                <typeMapping>TypedEmail_emailType=String</typeMapping>
                                <typeMapping>OptionallyTypedEmail_emailType=String</typeMapping>
                                <typeMapping>TypedPhone_phoneType=String</typeMapping>
                                <typeMapping>OptionallyTypedPhone_phoneType=String</typeMapping>
                            </typeMappings>
                            <globalProperties>
                                <globalProperty>models</globalProperty>
                                <globalProperty>apis</globalProperty>
                            </globalProperties>
                            <configOptions>
                                <delegatePattern>true</delegatePattern>
                                <generateBuilders>true</generateBuilders>
                                <openApiNullable>false</openApiNullable>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSwaggerUI>false</useSwaggerUI>
                                <enumPropertyNaming>legacy</enumPropertyNaming>
                                <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                                <disallowAdditionalPropertiesIfNotPresent>false</disallowAdditionalPropertiesIfNotPresent>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>