spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:${server.port:8080} # set to the deployed server URL
        client:
          or-client:
            registration:
              client-id: or-client
              client-secret: "{noop}secret"
              client-name: OneRoster Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - https://purl.imsglobal.org/spec/or/v1p2/scope/roster-core.readonly
                - https://purl.imsglobal.org/spec/or/v1p2/scope/roster.readonly
                - https://purl.imsglobal.org/spec/or/v1p2/scope/roster-demographics.readonly
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${server.port:8080}

# strip nulls in jackson serialization
  jackson:
    default-property-inclusion: NON_EMPTY
